# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20170602_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(default='', max_length=500),
        ),
    ]
