# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=25)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
