# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brothersportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], default='1st', help_text='Select year', max_length=25),
            preserve_default=False,
        ),
    ]
