# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('brothersportal', '0002_brother_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='city',
            field=models.CharField(default='1', help_text='Enter home/work city', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brother',
            name='company',
            field=models.CharField(blank=True, help_text='Enter current company (if applicable)', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='brother',
            name='major',
            field=models.CharField(default='1', help_text='Enter your primary major', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brother',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brother',
            name='pledge_class',
            field=models.CharField(default='1', help_text='Enter your pledge class (eg. Alpha, Beta, ...)', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brother',
            name='second_major',
            field=models.CharField(blank=True, help_text='Enter optional second major', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='brother',
            name='state',
            field=models.CharField(default='1', help_text='Enter home/work state', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brother',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('Alumni', 'Alumni')], default='1st', help_text='Select year', max_length=25),
        ),
    ]
