# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 17:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brothersportal', '0003_auto_20170523_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='grad_year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(2012)]),
        ),
        migrations.AlterField(
            model_name='brother',
            name='second_major',
            field=models.CharField(blank=True, help_text='Enter second major (if applicable)', max_length=25, null=True),
        ),
    ]
