# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brothersportal', '0004_auto_20170524_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('Alumni', 'Alumni')], default='1st', help_text='Select current year at UVA', max_length=25),
        ),
    ]
