# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brothersportal', '0005_auto_20170625_0214'),
        ('brothersportal', '0005_auto_20170526_0039'),
    ]

    operations = [
    ]
